local mc = require("multicursor-nvim")

mc.setup()

vim.keymap.set({ "n", "x" }, "<C-Up>", function ()
   mc.lineAddCursor(-1)
end)
vim.keymap.set({ "n", "x" }, "<C-Down>", function ()
   mc.lineAddCursor(1)
end)
vim.keymap.set({ "n", "x" }, "<Leader><Up>", function ()
   mc.lineSkipCursor(-1)
end)
vim.keymap.set({ "n", "x" }, "<Leader><Down>", function ()
   mc.lineSkipCursor(1)
end)

vim.keymap.set({ "n", "x" }, "<Leader>n", function ()
   mc.matchAddCursor(1)
end)
vim.keymap.set({ "n", "x" }, "<Leader>s", function ()
   mc.matchSkipCursor(1)
end)
vim.keymap.set({ "n", "x" }, "<Leader>N", function ()
   mc.matchAddCursor(-1)
end)
vim.keymap.set({ "n", "x" }, "<Leader>S", function ()
   mc.matchSkipCursor(-1)
end)

vim.keymap.set("n", "<C-LeftMouse>", mc.handleMouse)
vim.keymap.set("n", "<C-LeftDrag>", mc.handleMouseDrag)
vim.keymap.set("n", "<C-LeftRelease>", mc.handleMouseRelease)

vim.keymap.set({ "n", "x" }, "<C-q>", mc.toggleCursor)
